Repository sdnfv/openNetVM, pull requests merged in 2019-07, with the labels that each got.

#126 cJSON updates
  onvm/lib/cJSON.c
  onvm/lib/cJSON.h
Labels: dependency updates :arrow_double_up:

#149 Shared core functionality for messages
  docs/NF_Dev.md
  onvm/onvm_nflib/onvm_common.h
  onvm/onvm_nflib/onvm_nflib.c
Labels: enhancement :rocket:

#98 Add NFD library with multiple example NFs
  examples/NFD/Makefile
  examples/NFD/README.md
  examples/NFD/architecture.txt
  examples/NFD/dns_amplification_mitigation/DNSAmplificationMitigation.cpp
  examples/NFD/dns_amplification_mitigation/DNSAmplificationMitigationModel.txt
  examples/NFD/dns_amplification_mitigation/Makefile
  examples/NFD/dns_amplification_mitigation/README.md
  examples/NFD/dns_amplification_mitigation/go.sh
  examples/NFD/go.sh
  examples/NFD/heavy_hitter_detection/HHD.cpp
  examples/NFD/heavy_hitter_detection/HHDmodel.txt
  examples/NFD/heavy_hitter_detection/Makefile
  examples/NFD/heavy_hitter_detection/README.md
  examples/NFD/heavy_hitter_detection/go.sh
  examples/NFD/include/basic_classes.h
  examples/NFD/include/decode.h
  examples/NFD/lib/Makefile
  examples/NFD/lib/basic_classes.cpp
  examples/NFD/lib/basic_methods.cpp
  examples/NFD/napt/.gitignore
  examples/NFD/napt/Makefile
  examples/NFD/napt/NAPT.cpp
  examples/NFD/napt/README.md
  examples/NFD/napt/go.sh
  examples/NFD/napt/model.txt
  examples/NFD/stateful_firewall/.gitignore
  examples/NFD/stateful_firewall/Makefile
  examples/NFD/stateful_firewall/README.md
  examples/NFD/stateful_firewall/go.sh
  examples/NFD/stateful_firewall/model.txt
  examples/NFD/stateful_firewall/stateful_firewall.cpp
  examples/NFD/stateless_firewall/.gitignore
  examples/NFD/stateless_firewall/Makefile
  examples/NFD/stateless_firewall/README.md
  examples/NFD/stateless_firewall/go.sh
  examples/NFD/stateless_firewall/model.txt
  examples/NFD/stateless_firewall/stateless_firewall.cpp
  examples/NFD/super_spreader_detection/Makefile
  examples/NFD/super_spreader_detection/README.md
  examples/NFD/super_spreader_detection/SSD.cpp
  examples/NFD/super_spreader_detection/SSDmodel.txt
  examples/NFD/super_spreader_detection/go.sh
  examples/NFD/syn_flood_detection/Makefile
  examples/NFD/syn_flood_detection/README.md
  examples/NFD/syn_flood_detection/SYNFloodDetection.cpp
  examples/NFD/syn_flood_detection/SYNFloodDetectionModel.txt
  examples/NFD/syn_flood_detection/go.sh
  examples/NFD/udp_flood_mitigation/Makefile
  examples/NFD/udp_flood_mitigation/README.md
  examples/NFD/udp_flood_mitigation/UDPFloodMitagation.cpp
  examples/NFD/udp_flood_mitigation/UDPFloodMitagationModel.txt
  examples/NFD/udp_flood_mitigation/go.sh
  examples/start_nf.sh
  onvm/onvm_nflib/onvm_flow_table.h
Labels: new NF :artificial_satellite:
