Repository sdnfv/openNetVM, pull requests merged in 2019-06, with the labels that each got.

#127 [Bug Fix] Fix Double Decrement of NF Children Count
  onvm/onvm_mgr/onvm_nf.c
Labels: bug fix :bug:

#123 Fix CI Lint Verification
  ci/helper-functions.sh
Labels: CI :robot:, enhancement :rocket:

#129 [Bug Fix] Update API Call for Speed Tester pcap mode
  examples/speed_tester/speed_tester.c
Labels: bug fix :bug:

#131 [Bug Fix] Add NF Cleanup after Critical Errors
  examples/speed_tester/speed_tester.c
Labels: bug fix :bug:

#130 Stats alignment fixes
  onvm/onvm_mgr/onvm_stats.h
  onvm/onvm_nflib/onvm_nflib.c
Labels: bug fix :bug:

#128 Rename Shared CPU Mode to Shared Core Mode
  docs/NF_Dev.md
  examples/scaling_example/scaling.c
  examples/speed_tester/speed_tester.c
  onvm/onvm_mgr/main.c
  onvm/onvm_mgr/onvm_args.c
  onvm/onvm_mgr/onvm_init.c
  onvm/onvm_mgr/onvm_init.h
  onvm/onvm_mgr/onvm_stats.c
  onvm/onvm_mgr/onvm_stats.h
  onvm/onvm_nflib/onvm_common.h
  onvm/onvm_nflib/onvm_nflib.c
Labels: enhancement :rocket:

#132 [Bug Fix] Resolve Stats Print Order
  onvm/onvm_mgr/onvm_stats.c
Labels: bug fix :bug:

#124 Refactors Advanced Rings API/Examples
  docs/NF_Dev.md
  examples/scaling_example/README.md
  examples/scaling_example/scaling.c
  examples/speed_tester/README.md
  examples/speed_tester/speed_tester.c
  onvm/onvm_nflib/onvm_common.h
  onvm/onvm_nflib/onvm_nflib.c
  onvm/onvm_nflib/onvm_nflib.h
Labels: enhancement :rocket:

#136 Update Extra Verbose Stats Display
  onvm/README.md
  onvm/onvm_mgr/onvm_stats.c
  onvm/onvm_mgr/onvm_stats.h
Labels: bug fix :bug:

#125 Add Release Notes for OpenNetVM v19.05
  docs/NF_Dev.md
  docs/Releases.md
Labels: notes :notebook:

#142 [Bug Fix] Fix Typo in Stats Header
  onvm/onvm_mgr/onvm_stats.h
Labels: bug fix :bug:

#145 [Bug Fix] Fix Stats Header in Release Notes
  docs/Releases.md
Labels: bug fix :bug:

#141 Ci performance update
  ci/README.md
  ci/manager.sh
  ci/run_ci.sh
Labels: CI :robot:

#140 Allow CI Lint and Branch Checks for Unauthorized Users
  ci/helper-functions.sh
  ci/manager.sh
  ci/post-msg.py
  ci/webhook-receiver.py
Labels: CI :robot:

#143 Ci busy no more
  ci/webhook-receiver.py
Labels: CI :robot:

#147 Macros for running flow table lookup
  onvm/onvm_mgr/Makefile
  onvm/onvm_mgr/onvm_pkt.c
Labels: enhancement :rocket:
