Repository sdnfv/openNetVM, pull requests merged in 2019-05, with the labels that each got.

#113 Broken style guide fixes
  docs/Contributing.md
  style/styleguide.md
Labels: bug fix :bug:

#112 Check if ONVM_HOME environment variable is set
  onvm/onvm_nflib/Makefile
Labels: enhancement :rocket:

#116 [Bug Fix] Adds NF Ring Cleanup Logic On Shutdown
  onvm/onvm_mgr/onvm_nf.c
Labels: bug fix :bug:

#111 [Bug Fix] NF Advanced Ring Thread Process NF Shutdown Messages
  examples/scaling_example/scaling.c
  examples/speed_tester/speed_tester.c
Labels: bug fix :bug:

#114 Launch script
  examples/start_nf.sh
Labels: bug fix :bug:

#115 Update CI to Review Pull Requests
  ci/clone-and-checkout-pr.py
  ci/helper-functions.sh
  ci/manager.sh
  ci/post-msg.py
  ci/speed-tester-analysis.py
  ci/worker.sh
  style/gwclint.py
Labels: enhancement :rocket:

#117 Consolidates All NF Structs
  examples/aes_decrypt/aesdecrypt.c
  examples/aes_encrypt/aesencrypt.c
  examples/arp_response/arp_response.c
  examples/basic_monitor/monitor.c
  examples/bridge/bridge.c
  examples/firewall/firewall.c
  examples/flow_table/flow_table.c
  examples/flow_table/sdn.c
  examples/flow_table/sdn_pkt_list.h
  examples/flow_tracker/flow_tracker.c
  examples/load_balancer/load_balancer.c
  examples/load_generator/load_generator.c
  examples/ndpi_stats/ndpi_stats.c
  examples/nf_router/nf_router.c
  examples/payload_scan/payload_scan.c
  examples/scaling_example/scaling.c
  examples/simple_forward/forward.c
  examples/speed_tester/speed_tester.c
  examples/test_flow_dir/test_flow_dir.c
  onvm/onvm_mgr/main.c
  onvm/onvm_mgr/onvm_init.c
  onvm/onvm_mgr/onvm_init.h
  onvm/onvm_mgr/onvm_nf.c
  onvm/onvm_mgr/onvm_stats.c
  onvm/onvm_mgr/onvm_stats.h
  onvm/onvm_nflib/onvm_common.h
  onvm/onvm_nflib/onvm_nflib.c
  onvm/onvm_nflib/onvm_nflib.h
Labels: enhancement :rocket:, high priority :exclamation:

#122 [Bug Fix] Free Memory on ONVM_MGR Shutdown
  onvm/onvm_mgr/main.c
Labels: bug fix :bug:

#110 Added nf tag and core to stats
  onvm/onvm_mgr/onvm_stats.c
  onvm/onvm_mgr/onvm_stats.h
Labels: enhancement :rocket:
