Repository sdnfv/openNetVM, pull requests merged in 2019-04, with the labels that each got.

#84 Update install script huge page setup
  scripts/dpdk_helper_scripts.sh
  scripts/install.sh
  scripts/setup_environment.sh
Labels: bug fix :bug:

#65 Document dpdk tool for cleaning up huge pages
  docs/Install.md
Labels: documentation updates :book:

#94 Update DPDK Script Name in Install Docs
  docs/Install.md
Labels: documentation updates :book:

#76 Adds CI to the Public Repo
  ci/.gitignore
  ci/README.md
  ci/ci_busy.sh
  ci/clone-and-checkout-pr.py
  ci/manager.sh
  ci/webhook-receiver.py
  ci/worker.sh
Labels: enhancement :rocket:

#96 Packet number bug fix
  examples/speed_tester/speed_tester.c
Labels: bug fix :bug:

#99 Enforce 120 line length in linter
  CPPLINT.cfg
  ci/helper-functions.sh
  examples/speed_tester/speed_tester.c
  onvm/onvm_mgr/main.c
  style/gwclint.py
Labels: enhancement :rocket:

#104 onvm_pkt_parse_ip fix
  examples/arp_response/arp_response.c
  examples/load_balancer/load_balancer.c
  examples/nf_router/nf_router.c
  onvm/onvm_nflib/onvm_pkt_helper.c
Labels: bug fix :bug:

#103 Fix NF Tag memory allocation
  examples/speed_tester/speed_tester.c
  onvm/onvm_mgr/onvm_nf.c
  onvm/onvm_nflib/onvm_common.h
  onvm/onvm_nflib/onvm_nflib.c
Labels: bug fix :bug:

#102 Add some linter fixes
  examples/aes_decrypt/aes.h
  examples/aes_encrypt/aes.h
  examples/flow_table/flow_table.h
  examples/flow_table/msgbuf.h
  examples/flow_table/openflow.h
  examples/flow_table/sdn.c
  examples/flow_table/sdn.h
  examples/flow_table/sdn_pkt_list.h
  examples/flow_table/setupconn.h
  onvm/onvm_mgr/onvm_init.c
  onvm/onvm_nflib/onvm_common.h
  onvm/onvm_nflib/onvm_config_common.h
  onvm/onvm_nflib/onvm_msg_common.h
  onvm/onvm_nflib/onvm_nflib.c
  onvm/onvm_nflib/onvm_nflib.h
  onvm/onvm_nflib/onvm_sc_common.h
  onvm/onvm_nflib/onvm_sc_mgr.h
Labels: style fixes :pen:

#109 Fix memory leaks on NF shutdown
  onvm/onvm_nflib/onvm_nflib.c
Labels: enhancement :rocket:

#92 Reuse NF instance IDs
  onvm/onvm_mgr/main.c
  onvm/onvm_mgr/onvm_mgr.h
  onvm/onvm_mgr/onvm_nf.c
  onvm/onvm_mgr/onvm_nf.h
  onvm/onvm_nflib/onvm_common.h
Labels: enhancement :rocket:
