Repository sdnfv/openNetVM, pull requests merged in 2019-03, with the labels that each got.

#82 Json mem leak
  onvm/onvm_mgr/onvm_stats.c
Labels: bug fix :bug:

#85 Ensure system is up-to-date in installation guide
  docs/Install.md
Labels: documentation updates :book:

#77 Update Debugging Documentation
  docs/Debug.md
Labels: documentation updates :book:

#72 Upgrading from Ubuntu 14.04.1 to 18.04.1
  onvm/lib/cJSON.c
  onvm/onvm_mgr/onvm_init.c
  onvm/onvm_nflib/onvm_common.h
Labels: enhancement :rocket:

#88 [Bug Fix] Properly Terminate Started but not yet Running NFs
  onvm/onvm_mgr/onvm_nf.c
Labels: bug fix :bug:
