Repository sdnfv/openNetVM, pull requests merged in 2020-07, with the labels that each got.

#219 Default CPU Cores for Manager
  docs/Examples.md
  docs/Install.md
  onvm/README.md
  onvm/go.sh
Labels: enhancement :rocket:

#239 Pktgen documentation updates
  tools/Pktgen/README.md
Labels: documentation updates :book:

#216 Memory
  examples/flow_tracker/flow_tracker.c
  examples/load_balancer/load_balancer.c
  onvm/onvm_mgr/main.c
  onvm/onvm_mgr/onvm_stats.c
  onvm/onvm_nflib/onvm_config_common.c
  onvm/onvm_nflib/onvm_flow_table.c
  onvm/onvm_nflib/onvm_flow_table.h
  onvm/onvm_nflib/onvm_nflib.c
  onvm/onvm_nflib/onvm_pkt_helper.c
Labels: enhancement :rocket:, ready-for-gatekeeper :door:

#218 Python Script for JSON Config Files
  docs/Examples.md
  docs/NF_Dev.md
  examples/example_nf_deploy.json
  examples/run_group.py
Labels: enhancement :rocket:, ready-for-gatekeeper :door:

#224 Use NF data instead of global variables.
  examples/simple_fwd_tb/forward_tb.c
Labels: enhancement :rocket:, ready-for-gatekeeper :door:
