Repository sdnfv/openNetVM, pull requests merged in 2020-04, with the labels that each got.

#179 NF prints summary of its activity on shutdown
  examples/.gitignore
  onvm/onvm_nflib/onvm_nflib.c
  onvm/onvm_nflib/onvm_nflib.h
Labels: enhancement :rocket:, ready-for-gatekeeper :door:

#204 Update UDP packet information printing
  onvm/onvm_nflib/onvm_pkt_helper.c
Labels: bug fix :bug:, ready-for-gatekeeper :door:

#211 Update onvm_web documentation
  onvm_web/README.md
Labels: documentation updates :book:, ready-for-gatekeeper :door:

#205 Add check for validating ports
  examples/load_balancer/load_balancer.c
  examples/load_generator/load_generator.c
  examples/scaling_example/scaling.c
  examples/speed_tester/speed_tester.c
  onvm/go.sh
  onvm/onvm_nflib/onvm_common.h
Labels: bug fix :bug:, ready-for-gatekeeper :door:
