Repository sdnfv/openNetVM, pull requests merged in 2020-05, with the labels that each got.

#196 GitHub actions
  .github/workflows/Linter.yml
  .pylintrc
  .shellcheckrc
  style/git-difftool-changed-lines.sh
  style/github-action-style.md
  style/install-linters.sh
  style/run-lint.py
  style/run-lint.sh
Labels: CI :robot:, enhancement :rocket:, ready-for-gatekeeper :door:

#183 Bash Script Clean-Up
  examples/NFD/go.sh
  examples/go.sh
  examples/start_nf.sh
  onvm/go.sh
  onvm_web/build_web.sh
  onvm_web/start_web_console.sh
  scripts/docker.sh
  scripts/dpdk_helper_scripts.sh
  scripts/install.sh
  scripts/no_hyperthread.sh
  scripts/setup_environment.sh
  tools/Pktgen/openNetVM-Scripts/run-pktgen.sh
Labels: ready-for-gatekeeper :door:

#212 Advanced rings fix
  docs/NF_Dev.md
  examples/scaling_example/scaling.c
Labels: bug fix :bug:, documentation updates :book:, high priority :exclamation:

#202 Update Docker to Ubuntu 18
  docs/Docker.md
  examples/go.sh
  onvm/go.sh
  scripts/Dockerfile
  scripts/docker.sh
Labels: NeedsReleaseNote, dependency updates :arrow_double_up:

#209 Acorn Dependabot Update
  onvm_web/react-app/yarn.lock
  onvm_web/web-build/asset-manifest.json
  onvm_web/web-build/precache-manifest.066f61a06c4d9a9b74e77de8ce55ef9c.js
  onvm_web/web-build/precache-manifest.9e30993647e06e9411d5539e546b5a8f.js
  onvm_web/web-build/service-worker.js
Labels: dependency updates :arrow_double_up:
