Repository sdnfv/openNetVM, pull requests merged in 2020-06, with the labels that each got.

#221 DPDK Missing Python Dependencies
  docs/Install.md
  scripts/corehelper.py
  scripts/csv-analysis.py
Labels: bug fix :bug:

#229 Fix for Manager go.sh Incorrectly Comparing Ports Available
  onvm/go.sh
Labels: bug fix :bug:, ready-for-gatekeeper :door:

#235 Changing PR Template to have a reminder to merge to develop
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation updates :book:

#223 MAC address fix
  examples/load_generator/load_generator.c
  examples/speed_tester/speed_tester.c
Labels: bug fix :bug:

#227 Update stats for outgoing packets
  onvm/onvm_nflib/onvm_pkt_common.c
Labels: bug fix :bug:
